// vue/src/ProgressUp.vue
<template>
 <div>
  <div class="progress-up-wrapper">
     <div class='text-center'>
     <button @click="clearAll" class="clearButton" role="button">Clear all</button>
     </div>

     <form class="progress-up-form">
     <input ref="fileInput"  v-on:change="uploadAllFiles" class="file-input" type="file" name="myFiles" multiple hidden>
     <span @click="$refs.fileInput.click()" >
     <h2>Browse Files to Upload</h2>
     </span>
     </form>
  </div>

 <section class="progress-up-area">
  <div v-if="progressInfos">
      <div v-for="(progressInfo, index) in progressInfos"
        :key="index" >
       <li class="row">
          <div class='content'>
           <div class='details'>
            <span>{{progressInfo.fileName}}</span>
            <span class='percent'> {{progressInfo.percentage}} %</span>
           </div>
           <div class='progress-bar'>
                <div class="progress" :style="{ width: progressInfo.percentage + '%' }"> </div>
            </div>
            <span class="size">{{progressInfo.size}} Bytes</span>
          </div>
       </li>
      </div>
    </div>
   </section>

 </div>
</template>


<script>
import axios from "axios";
import config from './config.json';

export default {
  name: "ProgressUp",
  data() {
    return {
      selectedFiles: undefined,
      progressInfos: [],
      message: ""
    };
  },
  methods: {
  uploadFile(file, onUploadProgress) {
    let formData = new FormData();

    formData.append(config.filesArray, file);

    return axios.post(config.uploadURL, formData, {
      headers: {
        "Content-Type": "multipart/form-data"
      },
      onUploadProgress
    });
  },

    uploadProgress(idx, file) {
      this.progressInfos[idx] = { percentage: 0, fileName: file.name,
size: file.size };

      this.uploadFile(file, (event) => {
        this.progressInfos[idx].percentage = Math.round(100 * event.loaded / event.total);
      })
        .then((response) => {
          let prevMessage = this.message ? this.message + "\n" : "";
          this.message = prevMessage + response.data.message;
      });
    },

    clearAll() {
      this.progressInfos = []; 
    },

    uploadAllFiles(event) {
      this.progressInfos = []; 
      this.selectedFiles = event.target.files;
      this.message = "";
      for (let i = 0; i < this.selectedFiles.length; i++) {
        this.uploadProgress(i, this.selectedFiles[i]);
      }
    }
  }
};
</script>

<style scoped>
@import 'https://cdn.jsdelivr.net/gh/girish1729/progress-up/css/progress-up.css';
</style>

// react/src/ProgressUp.js
import React, {
    Fragment,
    useState
} from "react";
import axios from "axios";
import {
    FontAwesomeIcon
} from '@fortawesome/react-fontawesome';
import {
    solid
} from '@fortawesome/fontawesome-svg-core/import.macro';
import {filesArray, uploadURL} from "./config";

/*
UploadFile = {
    fileName ;
    size;
    progressPercent ;
};
*/

const ProgressUp: React.FunctionComponent = () => {

        //let [progFiles, setProg] = useState <Array<UploadFile>>([]);
        let [progFiles, setProg] = useState([]);
        const url = uploadURL;

        const clearAll = () => {
                setProg([]);
		console.log("clear All");
        };

        const uploadForm = async (fname: string, formData: FormData) => {
            await axios.post(url, formData, {
                headers: {
                    "Content-Type": "multipart/form-data",
                },
                onUploadProgress: (progEvent) => {
                    let v: number;
                    if (progEvent.total) {
                        v = (progEvent.loaded / progEvent.total) * 100;
                        console.log(v);
                    }
                    setProg((upl) => {
                        return upl.map((p) => {
                            if (p.fileName === fname) {
                                p.progressPercent = v;
                            }
                            return p;
                        });
                    });

                },
            }).then(function() {
                console.log("All files uploaded");
            });
        };

        const onFileUpload = (e: React.ChangeEvent < HTMLInputElement > ) => {
            const files = e.target.files;
            if (files) {
                for (let i = 0; i < files.length; i++) {
                    const formData = new FormData();
                    const fileName = files[i].name;
                    const size = files[i].size;
                    formData.append(filesArray, files[i]);
                    progFiles.push({
                        fileName,
                        size,
                        progressPercent: 0
                    });
                    uploadForm(fileName, formData);
                }
                setProg(progFiles);
            }
        };

  return (
  <Fragment>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/girish1729/progress-up/css/progress-up.css" />
  <div className="progress-up-wrapper">
	  <header>Progress.up file upload </header>
	  <div className='text-center'>
		  <button onClick={clearAll} className="clearButton" role="button">Clear all</button>
	  </div>

		  <input id="inputFile" onChange={onFileUpload} className="file-input" type="file" name="myFiles" multiple hidden></input>
	  <form className="progress-up-form">
		  <label htmlFor="inputFile" className="button">
		  <FontAwesomeIcon icon={solid('cloud-upload-alt')} size='10x' />
		  <h2>Browse Files to Upload</h2>
	</label>
	  </form>
  </div>

  <div id="prog">
  <section className="progress-up-area">
  {progFiles.length > 0
  ? (
  progFiles.map(({fileName, progressPercent, size}) => (
  <li className="row" key={fileName} >
	  <FontAwesomeIcon icon={solid('file-alt')} />
	  <div className="content">
		  <div className="details">
			  <span className="name">{fileName} </span>
			  <span className="percent">{progressPercent} %</span>
		  </div>
		  <div className="progress-bar">
			  <div  className="progress" style={{width:
				progressPercent + '%'}}></div>
		  </div>
		  <span className="size">{size} Bytes</span>
	  </div>
  </li>
  ))
  )
  : <p>HTML5 Multiple upload progress indicator </p>}
  </section>
  </div>

 </Fragment>
  );
};

export default ProgressUp;
