// vue/src/App.vue
<template>
  <div id="app">
    <div class="container" style="width:600px">
      <div style="margin: 20px">
        <h1>progress.up | HTML5 multi file upload progress bar</h1>
        <h2>Vue.js plugin </h2>
      </div>
      <upload-files-progress></upload-files-progress>
    </div>
  </div>
</template>

<script>
import UploadFilesProgress from "./components/uploadFilesProgress";

export default {
  name: "App",
  components: {
    UploadFilesProgress
  }
};
</script>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'progress.up | HTML5 multi file upload Angular plugin';
}

<div class="container" style="width:600px">
  <div style="margin: 20px">
    <h3>Progress.up | HTML5 multi file progress bar Angular plugin</h3>
  </div>

  <app-upload-files></app-upload-files>
</div>
